data_dir: "" #Insert your data_directory here - make sure to have / at end
output_dir: "" #Insert where to put output data - make sure to have / at end
file_type: ".parquet" #Insert your file type here - acceptable inputs are .csv, .csv.gz, .parquet, .fst
institution: "" #Insert your institution here
